name: Deliver
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.CICD_TOOLING_FULL_ACCESS_KEY }}
        aws-secret-access-key: ${{ env.CICD_TOOLING_FULL_ACCESS_SECRET }}
        aws-region: "eu-west-1"
    - uses: google-github-actions/setup-gcloud@master
    - name: deliver
      shell: bash
      run: make deliver