name: Setup Rust with cache
description: Install Rust with the desired version and cache
inputs:
  rust-version:
    description: 'version'
    required: false
    default: '1.58.1'
runs:
  using: composite
  steps:
    - uses: Swatinem/rust-cache@v1
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      id: toolchain
      with:
        toolchain: ${{ inputs.rust-version }}
        override: true
        target: x86_64-unknown-linux-gnu
        components: clippy,rustfmt
    - name: Install cross
      shell: bash
      run: cargo install cross
